### PR TITLE
Add build instructions to README

### PR DESCRIPTION
**Pull request by daniel-lerch**
I already thought about adding such instructions earlier but as users start to be interested in this project, you can't miss these instructions anymore.

### CODE REVIEW

**Comment by Twometer** [comment]
Nice!

**Comment by vivandoshi08** [comment]
Thanks for the build instructions. I will now try to make the camera system and Polus map with blender. Will keep you guys updated. Great work by the way.

**Comment by vivandoshi08** [comment]
There is a slight issue. In gradle, the dependencies don't download for neko engine since there is 502 bad gateway. How to fix?

**Review by vivandoshi08 — COMMENTED** [review]
need to fix the gradle links for neko engine, they have 502 bad gateway

**Pull request merged**
